### ISSUE TITLE
SimulationStructure for Genomes

### ISSUE THREAD

**Issue by yeldiRium** [strangedev/NEAT_PyGenetics#1]
We need a dedicated genome structure for simulations.
The structure should be fast to use, while storage efficiency is the lesser priority.

This is a preliminary design:
![simulationgenome](https://cloud.githubusercontent.com/assets/11889637/12812525/ba8a2fba-cb32-11e5-9782-3a052a9a5bb0.png)

**Comment by yeldiRium** [comment]
The Genomes and Nodes will be stored in seperate Repositories, allowing access to them via id. (Flyweight pattern)
This way, Genomes can share Nodes without taking up too much storage.

**Comment by strangedev** [comment]
Is it really a good idea to classify nodes as cycle nodes? 
Node cannot be the cause for cycles and are rarely purely cycle nodes. Most of the time they are also part of the dag. Instead, we should mark edges inside the Node class as cycle edges.

**Comment by yeldiRium** [comment]
Currently in the SimulationGenome there are no Edge-Objects. There are only nodes objects that store references to other nodes. Thus we have to mark the Nodes containing the "edges".
Since CycleNodes inherit from the usual nodes, it does not interfere with their behaviour inside the dag. It only enables them to be targeted specifically for firing their cycle forming edges.

**Comment by yeldiRium** [comment]
Since python floating point arithmetic has the same flaws as every kind of floating point arithmetic, I'm trying to replace Floats with Fractions for more accuracy.

**Comment by yeldiRium** [comment]
Tests are successful. Imo this can be closed.

Although - analogue to #3 this can be expanded by standard operators.

**Comment by strangedev** [comment]
Class implemented, now waiting for debugging.
