### ISSUE TITLE
AnalysisStructure for Genomes

### ISSUE THREAD

**Issue by yeldiRium** [strangedev/NEAT_PyGenetics#3]
We need a dedicated structure for the analysis of genomes.
The structure should be lightweight, but easily traversable and easy to check for cycles etc.
The currently best idea for this is an adjacency list.

**Comment by yeldiRium** [comment]
As an addition to the current state of the Analysis Genome we need a list of the starting nodes, since we need to know where to start the DFS. At the moment the Analysis Genome only contains the whole adjacency matrix.

**Comment by yeldiRium** [comment]
The AnalysisGenome now correctly constructs itself from a given StorageGenome (except for the problem that there is no GeneRepository yet - tests with mocks run smoothly though).
After some more testing I'd mark this as finished.

It could although be expanded a bit more - standard things like an __eq__ operator and other basic python methods could be added. This should possibly be done everywhere sometime.

**Comment by strangedev** [comment]
Class implemented, now waiting for debugging.
