### ISSUE TITLE
Genome Analyzer

### ISSUE THREAD

**Issue by yeldiRium** [strangedev/NEAT_PyGenetics#4]
The Genome Analyzer performs different tasks on Genomes in the AnalysisStructure.
The currently planned analysis tasks are:
- test for coherency
  - finding sources and sinks in the hidden layer (and removing them)
- finding cycles (and marking them)
- marking Genes as disables

The Genome analyzer should return a diff object on request. This diff object should contain information about what in the graph has to change according to the given rules. If there are source or sinks found, for example, they should be contained in the diff object as "to be removed", so that they can be removed from the StorageStructure afterwards.

**Comment by yeldiRium** [comment]
Update:

Rename of return object from DiffObject to AnalysisResult.
The result should contain:
- a list of all genes that close cycles
- a list of all disabled genes (genes that connect nodes that are already transitively connected)
- a topologically sorted list of all not cycle closing genes
- a topologically sorted list of all cycle closing genes

**Comment by yeldiRium** [comment]
The genome analyzer is basically finished. The only thing left to do is to identify genes that should be disabled.
What are the criteria for that?

**Comment by yeldiRium** [comment]
Also it would be very neat (lol) to have more tests for the GenomeAnalyst. I suggest that some people draw some random graphs and find the cycle_edges and topological order etc. by hand and add that to the tests.
One already exists and can be used as an example.

**Comment by strangedev** [comment]
Class implemented, now waiting for debugging.
