### ISSUE TITLE
Gene Repository

### ISSUE THREAD

**Issue by yeldiRium** [strangedev/NEAT_PyGenetics#5]
The Gene Repository collects and distributes Genes.
How these are stored exacty is not yet decided, but it should be persistent.

Genes should be accessible via getGene(geneID) or something like that. Also the repository should provide the possibility to search for Genes starting or ending in a specific node (for reusage).

I recommend sqlite for testing and prototyping, then switching to MySQL later on.
I haven't toyed with nosql databases yet - maybe they are a viable in this case.

Thoughts and opinions?

**Comment by yeldiRium** [comment]
The gene repository needs to be able to find connecting vertices.
I.e. if there is a gene (25, 83) and we want to mutate it (replace it with two new genes), we want to look up, if there are already two genes that fulfill this constraint (e.g. (25, 37), (37, 83)) and return the connecting vertex' id.

**Comment by strangedev** [comment]
Class implemented, now waiting for debugging.
