### ISSUE TITLE
Genome Repository

### ISSUE THREAD

**Issue by yeldiRium** [strangedev/NEAT_PyGenetics#6]
The Genome Repository is basically the container for the current population. Old Genomes should not be thrown away, but marked as old and out of use.

**Comment by yeldiRium** [comment]
Update: we use two collections for StorageGenomes.
A legacy collection that contains all the dead genomes and an active collection that only contains genomes that are in the current population.
This way it is faster to query for living Genomes.

Looking up if a specific Genome already exists should take about as long as with only one collection.

**Comment by strangedev** [comment]
Class implemented, now waiting for debugging.
