### ISSUE TITLE
Simulator

### ISSUE THREAD

**Issue by yeldiRium** [strangedev/NEAT_PyGenetics#7]
The simulator uses an arbitrary simulation (in strangedev's case his prg-1 python project, I want to use 2048) to receive inputs for a genome and to test the outputs of the genome.
The simulation then has to prvide a fitness for the tested genome.

For this we need a really abstract structure.
A Simulator should have this interface:
 - run(genome) // genome in SimulationStructure
where run returns the fitness of the genome.

Very abstract ;D

**Comment by strangedev** [comment]
The simulator should also be able to accept a set of different genomes to be simulated simultaneously in order to simulate social behaviour of different individuals/species.

("Simul-"-count: 4 ^^)

The whole gene pool could be passed as a list of genomes, the fitness values could be returned as dictionary (genome/genome_id? -> fitness_value)

**Comment by yeldiRium** [comment]
Good idea. I didn't think about simulations that require/support multiple participants.
Generally it should also be possible to run multiple independet simulations in tandem aka multithreading. Maybe for the future.

**Comment by yeldiRium** [comment]
We should be able to plug in simulations as simply as possible.
Therefore i suggest creatimga basic layout for all simulation modules and a common interface for interaction with the mediator, a.k.a. the SimulationRunner.
The SimulationRunner should load the simulation module and start the simulation with whatever it needs.
It reads the informstion needed from a config file inside the simulation module.
This config file should contain information about:
* number and labels of input nodes
* number and labels of output nodes
* number of genomes needed for a simulation (for cases when simulations interact inside a simulation)

The values for input and output nodes are also used to generate an initial random population and as constraints for mutation/breeding.

to be expanded.

**Comment by strangedev** [comment]
Concept was implemented as part of the NEATClient.
