### ISSUE TITLE
Genome Clustering

### ISSUE THREAD

**Issue by yeldiRium** [strangedev/NEAT_PyGenetics#8]
We want to cluster our population into species to encourage inbreeding.
Inbreeding is used to prevent "good ideas" from being killed befor they can develop. If a change in a genome, that will eventually lead to greatness, initially decreases the fitness, it would be discarded.
Because of that, we take similar genomes and cluster them, leaving the genomes in clusters alive, even if their fitness is low. Cluster with a low overall fitness produce less offspring, so we can focus our resources on better clusters, but they continue to exists, so they may improve their "ideas".

Therefore, we need a way to cluster our genomes. After breeding for a while inside these clusters, we breed two whole clusters together, thus (probably) creating a new, third, cluster. Afterwards, we recluster everything and keep on inbreeding.

**Comment by yeldiRium** [comment]
k-nearest-neighbors algorithm could be what we need

**Comment by strangedev** [comment]
Clustering is implemented, improvements go in separate issues.
